// Generates supabase/seed.sql from the prototype's mock JSON datasets —
// the exact content every QA pass ran against, now as Postgres rows.
// Deterministic and re-runnable (truncate + insert per table).
//
// Run: node scripts/gen-seed.mjs   (then `npx supabase db push && psql -f supabase/seed.sql`,
// or paste into the Supabase SQL editor — see supabase/README.md)
import fs from 'node:fs';

const read = (f) => JSON.parse(fs.readFileSync(new URL(`../src/data/${f}.json`, import.meta.url), 'utf8'));
const institutions = read('institutions');
const courses = read('courses');
const scholarships = read('scholarships');
const ambassadors = read('ambassadors');
const community = read('community');
const support = read('support');
const safety = read('safety');
const col = read('costOfLiving');
const attractions = read('attractions');
const badgesI18n = JSON.parse(fs.readFileSync(new URL('../src/i18n/en.json', import.meta.url), 'utf8')).rewards;

const q = (v) => {
  if (v === null || v === undefined || v === '') return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const j = (v) => `'${JSON.stringify(v ?? []).replace(/'/g, "''")}'::jsonb`;

const out = [];
out.push('-- GENERATED by scripts/gen-seed.mjs — do not edit by hand.');
out.push('-- Content-identical to the mock JSON the prototype QA passes ran against.');
out.push('begin;');
out.push(`truncate public.recognition_matrix, public.entry_requirements, public.nearby_attractions,
  public.ambassador_posts, public.shorts, public.messages, public.intake_groups,
  public.scholarships, public.courses, public.ambassadors, public.institutions,
  public.cost_of_living, public.embassy_directory, public.support_team, public.badges
  restart identity cascade;`);

// ---- institutions ---------------------------------------------------------
for (const i of institutions) {
  out.push(`insert into public.institutions
    (id, name, short_name, type, country, city, is_verified_partner, tagline, founded, students,
     website, wikipedia, logo, qs_rank, languages, campuses, photos) values
    (${q(i.id)}, ${q(i.name)}, ${q(i.short)}, ${q(i.type)}, ${q(i.country)}, ${q(i.city)},
     ${q(Boolean(i.verifiedPartner))}, ${q(i.tagline)}, ${q(i.founded)}, ${q(i.students)},
     ${q(i.website)}, ${q(i.wikipedia)}, ${q(i.logo)}, ${q(i.ranking)}, ${j(i.languages)},
     ${j(i.campuses)}, ${j(i.images)});`);
}

// ---- courses + entry_requirements + recognition ---------------------------
for (const c of courses) {
  out.push(`insert into public.courses
    (id, institution_id, name, field, level, campus_city, country, duration_years,
     semesters_per_year, annual_tuition_local, tuition_per_semester, tuition_currency,
     application_fee, one_off_fees, required_documents, local_requirement_note,
     english_requirement, intake_dates, selectivity, pathway_for) values
    (${q(c.id)}, ${q(c.institutionId)}, ${q(c.name)}, ${q(c.field)}, ${q(c.level)},
     ${q(c.campusCity)}, ${q(c.country)}, ${q(c.durationYears)}, ${q(c.semestersPerYear)},
     ${q(c.tuitionPerYear)}, ${q(c.tuitionPerSemester)}, ${q(c.currency)}, ${q(c.applicationFee)},
     ${j(c.oneOffFees)}, ${j(c.requiredDocuments)}, ${q(c.localRequirementNote)},
     ${j(c.english)}, ${j(c.intakes)}, ${q(c.selectivity)}, ${j(c.pathwayFor)});`);
  for (const [sys, r] of Object.entries(c.requirements ?? {})) {
    out.push(`insert into public.entry_requirements (course_id, qualification_system, requirement_text, min_value)
      values (${q(c.id)}, ${q(sys)}, ${q(r.display ?? '')}, ${q(r.min)});`);
  }
  for (const [home, rec] of Object.entries(c.recognition ?? {})) {
    out.push(`insert into public.recognition_matrix (course_id, home_country, is_recognized)
      values (${q(c.id)}, ${q(home)}, ${q(Boolean(rec))});`);
  }
}

// ---- scholarships ---------------------------------------------------------
for (const s of scholarships) {
  out.push(`insert into public.scholarships
    (id, name, provider, destination_country, coverage_type, percent_tuition,
     eligibility_note, eligible_nationalities, fields, amount, currency, stipend_monthly, link, deadline) values
    (${q(s.id)}, ${q(s.name)}, ${q(s.provider)}, ${q(s.destinationCountry)}, ${q(s.coverageType)},
     ${q(s.percentTuition)}, ${q(s.eligibilityNote)}, ${j(s.nationalities)}, ${j(s.fields)},
     ${q(s.amount)}, ${q(s.currency)}, ${q(s.stipendMonthly)}, ${q(s.link)}, ${q(s.deadline)});`);
}

// ---- cost of living -------------------------------------------------------
for (const c of col) {
  out.push(`insert into public.cost_of_living
    (city, country, rent_monthly, rent_options, food_monthly, transport_monthly,
     utilities_monthly, eating_out_meal, insurance_yearly, visa_fee_oneoff, currency,
     last_verified, verified_by) values
    (${q(c.city)}, ${q(c.country)}, ${q(c.rentMonthly)}, ${j(c.rentOptions)}, ${q(c.foodMonthly)},
     ${q(c.transportMonthly)}, ${q(c.utilitiesMonthly)}, ${q(c.eatingOutMeal)}, ${q(c.insuranceYearly)},
     ${q(c.visaFeeOneOff)}, ${q(c.currency)}, ${q(c.lastVerified)}, ${j(c.verifiedBy)});`);
}

// ---- attractions ----------------------------------------------------------
for (const a of attractions) {
  out.push(`insert into public.nearby_attractions
    (id, institution_id, name, type, distance_minutes, description, image_url, tips,
     rating, review_count, review_snippet, photos) values
    (${q(a.id)}, ${q(a.institutionId)}, ${q(a.name)}, ${q(a.type)}, ${q(a.distanceMinutes)},
     ${q(a.description)}, ${q(a.image)}, ${j(a.tips)}, ${q(a.rating)}, ${q(a.reviewCount)},
     ${q(a.reviewSnippet)}, ${j(a.photos)});`);
}

// ---- ambassadors + posts --------------------------------------------------
for (const a of ambassadors) {
  out.push(`insert into public.ambassadors (id, name, institution_id, home_country, course, year, avatar_url, bio)
    values (${q(a.id)}, ${q(a.name)}, ${q(a.institutionId)}, ${q(a.homeCountry)}, ${q(a.courseName)}, ${q(a.year)}, ${q(a.avatar)}, ${q(a.bio)});`);
  for (const p of a.posts ?? []) {
    out.push(`insert into public.ambassador_posts
      (id, ambassador_id, institution_id, caption, media_urls, likes, posted_date) values
      (${q(`${a.id}-${p.id}`)}, ${q(a.id)}, ${q(a.institutionId)}, ${q(p.text)}, ${j(p.image ? [p.image] : [])}, ${q(p.likes ?? 0)}, ${q(p.date)});`);
  }
}

// ---- shorts ---------------------------------------------------------------
for (const s of support.shorts ?? []) {
  out.push(`insert into public.shorts
    (id, ambassador_id, institution_id, title, thumbnail_url, duration_sec, view_count, is_reality_check) values
    (${q(s.id)}, ${q(s.ambassadorId)}, ${q(s.institutionId)}, ${q(s.title)}, ${q(s.thumb)},
     ${q(s.duration)}, ${q(s.views)}, ${q(Boolean(s.reality))});`);
}

// ---- intake groups + demo chatter ----------------------------------------
for (const g of community.intakeGroups ?? []) {
  out.push(`insert into public.intake_groups (id, institution_id, name, intake_label, member_count)
    values (${q(g.id)}, ${q(g.institutionId)}, ${q(g.name)}, ${q(g.intake)}, ${q(g.members)});`);
}
for (const m of community.groupMessages ?? []) {
  // Deterministic pseudo-uuid per demo author; sender display is denormalized.
  out.push(`insert into public.messages (group_id, sender_id, sender_type, sender_name, sender_avatar, body)
    values (${q(m.groupId)}, (md5(${q(`seed:${m.author}`)}))::uuid, 'student', ${q(m.author)}, ${q(m.avatar)}, ${q(m.text)});`);
}

// ---- embassies ------------------------------------------------------------
for (const [dest, homes] of Object.entries(safety.embassies ?? {})) {
  for (const [home, e] of Object.entries(homes)) {
    if (!e) continue; // null marks "no mission for this pair" in the dataset
    out.push(`insert into public.embassy_directory
      (home_country, destination_country, city, name, address, phone, emergency_phone) values
      (${q(home)}, ${q(dest)}, ${q(e.city)}, ${q(e.name)}, ${q(e.address)}, ${q(e.phone)}, ${q(e.afterHours)});`);
  }
}

// ---- support team + badges ------------------------------------------------
for (const t of support.team ?? []) {
  out.push(`insert into public.support_team (id, name, role, avatar_url, phone, email)
    values (${q(t.id)}, ${q(t.name)}, ${q(t.role)}, ${q(t.avatar)}, ${q(t.phone)}, ${q(t.email)});`);
}
const BADGES = ['explorer', 'aspirant', 'prepper', 'applicant', 'offer', 'grad'];
BADGES.forEach((b, i) => {
  out.push(`insert into public.badges (id, code, name, description, journey_stage)
    values (${q(b)}, ${q(b)}, ${q(badgesI18n[`badge_${b}`] ?? b)}, ${q(badgesI18n[`badgeDesc_${b}`] ?? null)}, ${i + 1});`);
});

out.push('commit;');
fs.writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log(`seed.sql written: ${out.length} statements`);
console.log(`institutions=${institutions.length} courses=${courses.length} scholarships=${scholarships.length} col=${col.length} attractions=${attractions.length} ambassadors=${ambassadors.length} groups=${community.intakeGroups.length} messages=${community.groupMessages.length}`);
